# Generated by Django 5.2.8 on 2025-11-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.TextField()),
                ('nombre', models.TextField()),
                ('clase', models.TextField()),
                ('sexo', models.TextField()),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('numero_pasaporte', models.IntegerField()),
                ('direccion', models.TextField()),
                ('numero_telefono', models.IntegerField()),
                ('numero_movil', models.IntegerField()),
                ('email_alumno', models.TextField(default='emailalum@email.com')),
                ('email_padres', models.TextField(default='emailpadre@email.com')),
                ('profesion_padre', models.TextField()),
                ('profesion_madre', models.TextField()),
                ('edad_hermanos', models.IntegerField(blank=True, null=True)),
                ('edad_hermanas', models.IntegerField(blank=True, null=True)),
                ('mascotas_tener', models.BooleanField(default=False)),
                ('tipo_mascota', models.TextField(blank=True)),
                ('problemas_salud', models.TextField(blank=True)),
                ('es_vegetariano', models.BooleanField(default=False)),
                ('pref_intercambio', models.TextField(blank=True)),
                ('puede_alojar', models.BooleanField(default=False)),
                ('larga_duracion', models.BooleanField(default=False)),
                ('firma_alumno', models.TextField(blank=True)),
                ('firma_padres', models.TextField(blank=True)),
            ],
        ),
    ]
