# Generated by Django 5.2.8 on 2025-11-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='pref_intercambio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
