# Generated by Django 5.2.8 on 2025-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_alumno_pref_intercambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='firma_alumno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='firma_padres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
